Repository RAF-SI-2024/Banka-3-Frontend, pull requests merged in 2025-06, with the labels that each got.

#189 Fix reset password submit button text
  App/src/app/components/password-reset/password-reset.component.html
Labels: approved, lgtm

#190 pagination fix
  App/src/app/components/payments/payment-details/payment-details.component.html
  App/src/app/components/payments/payment-details/payment-details.component.ts
  App/src/app/components/stocks/active-offers/active-offers.component.html
  App/src/app/components/stocks/active-offers/active-offers.component.ts
  App/src/app/components/stocks/my-orders/my-orders.component.html
  App/src/app/components/stocks/my-orders/my-orders.component.ts
  App/src/app/components/stocks/order-overview/order-overview.component.html
  App/src/app/components/stocks/order-overview/order-overview.component.ts
  App/src/app/components/stocks/otc-offers-list/otc-offers-list.component.html
  App/src/app/components/stocks/otc-offers-list/otc-offers-list.component.ts
Labels: size/XL, approved, lgtm

#192 pagination added
  App/src/app/components/payments/payment-details/payment-details.component.html
  App/src/app/components/stocks/settled-contracts/settled-contracts.component.html
  App/src/app/components/stocks/settled-contracts/settled-contracts.component.ts
Labels: size/L, approved, lgtm

#193 Fix pagination, add error handling to user creation
  App/src/app/components/client/register-user/register-user.component.ts
  App/src/app/components/employee/register-employee/register-employee.component.ts
  App/src/app/components/payments/payment-details/payment-details.component.html
  App/src/app/components/payments/payment-details/payment-details.component.ts
  App/src/app/components/stocks/order-overview/order-overview.component.html
  App/src/app/components/stocks/order-overview/order-overview.component.ts
  App/src/app/services/order.service.ts
Labels: approved, lgtm, size/M

#194 Remove all non working otc pagination
  App/src/app/components/stocks/active-offers/active-offers.component.html
  App/src/app/components/stocks/active-offers/active-offers.component.ts
  App/src/app/components/stocks/otc-offers-list/otc-offers-list.component.html
  App/src/app/components/stocks/otc-offers-list/otc-offers-list.component.ts
  App/src/app/components/stocks/settled-contracts/settled-contracts.component.html
  App/src/app/components/stocks/settled-contracts/settled-contracts.component.ts
Labels: approved, lgtm, size/M
