Repository RAF-SI-2024/Banka-3-Frontend, pull requests merged in 2025-03, with the labels that each got.

#63 add owners file
  OWNERS
Labels: size/XS, approved, lgtm

#61 F 58 ispravka svega iz sprinta2
  App/src/app/components/account-management/account-management.component.html
  App/src/app/components/account-management/account-management.component.ts
  App/src/app/components/client-portal/client-portal.component.html
  App/src/app/components/client-portal/client-portal.component.ts
  App/src/app/components/navbar/navbar.component.html
  App/src/app/components/transfer/transfer.component.ts
  App/src/app/services/account.service.ts
Labels: approved, lgtm

#62 F 54 podnosenje zahteva za kredit
  App/src/app/app-routing.module.ts
  App/src/app/components/client-portal/client-portal.component.ts
  App/src/app/components/loan-request/loan-request.component.css
  App/src/app/components/loan-request/loan-request.component.html
  App/src/app/components/loan-request/loan-request.component.spec.ts
  App/src/app/components/loan-request/loan-request.component.ts
  App/src/app/login/login.component.ts
  App/src/app/models/loan-request.model.ts
  App/src/app/services/auth.service.ts
  App/src/app/services/loan-request.service.ts
Labels: size/L, approved, lgtm

#65 Novo placanje napravljeno
  App/src/app/app-routing.module.ts
  App/src/app/components/new-payment/new-payment.component.css
  App/src/app/components/new-payment/new-payment.component.html
  App/src/app/components/new-payment/new-payment.component.ts
  App/src/app/models/payment.model.ts
  App/src/app/services/payment.service.ts
  package-lock.json
  package.json
Labels: size/L, approved, lgtm

#68 Login fix
  App/src/app/app-routing.module.ts
  App/src/app/components/account-management/account-management.component.ts
  App/src/app/components/navbar/navbar.component.html
  App/src/app/components/new-payment/new-payment.component.ts
  App/src/app/components/welcome/welcome.component.html
  App/src/app/components/welcome/welcome.component.ts
  App/src/app/login/login.component.ts
Labels: approved, lgtm, size/S

#60 Uradjen payment servis
  App/src/app/app-routing.module.ts
  App/src/app/components/new-transaction/new-transaction.component.css
  App/src/app/components/new-transaction/new-transaction.component.html
  App/src/app/components/new-transaction/new-transaction.component.ts
  App/src/app/components/transaction-details/transaction-details.component.css
  App/src/app/components/transaction-details/transaction-details.component.html
  App/src/app/components/transaction-details/transaction-details.component.ts
  App/src/app/components/transaction-list/transaction-list.component.css
  App/src/app/components/transaction-list/transaction-list.component.html
  App/src/app/components/transaction-list/transaction-list.component.ts
  App/src/app/models/create-payment-dto.ts
  App/src/app/models/payment-details-dto.ts
  App/src/app/models/payment-overview-dto.ts
  App/src/app/services/payment.service.ts
Labels: size/XL, approved, lgtm

#71 Uradjeno kreiranje i blokiranje kartice
  App/src/app/app-routing.module.ts
  App/src/app/components/cards/cards.component.css
  App/src/app/components/cards/cards.component.html
  App/src/app/components/cards/cards.component.ts
  App/src/app/components/create-card/create-card.component.css
  App/src/app/components/create-card/create-card.component.html
  App/src/app/components/create-card/create-card.component.ts
  App/src/app/services/card.service.ts
  package-lock.json
  package.json
Labels: size/L, approved, lgtm

#80 F 55 loan portal
  App/src/app/app-routing.module.ts
  App/src/app/components/loans/loans.component.css
  App/src/app/components/loans/loans.component.html
  App/src/app/components/loans/loans.component.spec.ts
  App/src/app/components/loans/loans.component.ts
  App/src/app/models/loan-dto.model.ts
  App/src/app/services/loan.service.spec.ts
  App/src/app/services/loan.service.ts
Labels: size/XL, approved, lgtm

#79 F x error fixing v1
  App/src/app/app-routing.module.ts
  App/src/app/components/account-creation/account-creation.component.ts
  App/src/app/components/account-management/account-management.component.html
  App/src/app/components/account-management/account-management.component.ts
  App/src/app/components/cards/cards.component.ts
  App/src/app/components/client-portal/client-portal.component.css
  App/src/app/components/client-portal/client-portal.component.html
  App/src/app/components/client-portal/client-portal.component.ts
  App/src/app/components/create-foreign-currency-account/create-foreign-currency-account.component.css
  App/src/app/components/create-foreign-currency-account/create-foreign-currency-account.component.html
  App/src/app/components/create-foreign-currency-account/create-foreign-currency-account.component.ts
  App/src/app/components/loan-request/loan-request.component.ts
  App/src/app/components/new-payment/new-payment.component.ts
  App/src/app/components/new-transaction/new-transaction.component.ts
  App/src/app/components/register-user/register-user.component.html
  App/src/app/components/register-user/register-user.component.ts
  App/src/app/components/shared/pagination/pagination.component.ts
  App/src/app/components/users/users.component.html
  App/src/app/components/users/users.component.ts
  App/src/app/guards/auth-guard.guard.ts
Labels: size/L, approved, lgtm

#81 F Refactor Employees and client portal
  App/src/app/app-routing.module.ts
  App/src/app/components/client-portal/client-portal.component.html
  App/src/app/components/client-portal/client-portal.component.ts
  App/src/app/components/edit-employee/edit-employee.component.css
  App/src/app/components/edit-employee/edit-employee.component.html
  App/src/app/components/edit-employee/edit-employee.component.ts
  App/src/app/components/register-employee/register-employee.component.css
  App/src/app/components/register-employee/register-employee.component.html
  App/src/app/components/shared/aside/aside.component.html
  App/src/app/components/shared/button/button.component.css
  App/src/app/components/shared/button/button.component.html
  App/src/app/components/shared/input-text/input-text.component.css
  App/src/app/components/shared/input-text/input-text.component.html
  App/src/app/components/shared/select/select.component.css
  App/src/app/components/shared/select/select.component.html
  App/src/styles.css
Labels: size/L, approved, lgtm

#82 F x error fixing v2
  App/src/app/app-routing.module.ts
  App/src/app/components/account-creation/account-creation.component.ts
  App/src/app/components/account-management/account-management.component.html
  App/src/app/components/cards/cards.component.html
  App/src/app/components/cards/cards.component.ts
  App/src/app/components/loan-request/loan-request.component.ts
  App/src/app/components/new-payment/new-payment.component.css
  App/src/app/components/new-payment/new-payment.component.html
  App/src/app/components/new-payment/new-payment.component.ts
  App/src/app/components/new-transaction/new-transaction.component.ts
  App/src/app/components/payment-details/payment-details.component.css
  App/src/app/components/payment-details/payment-details.component.html
  App/src/app/components/payment-details/payment-details.component.spec.ts
  App/src/app/components/payment-details/payment-details.component.ts
  App/src/app/components/recipients/recipients.component.css
  App/src/app/components/recipients/recipients.component.html
  App/src/app/components/recipients/recipients.component.ts
  App/src/app/components/shared/aside/aside.component.css
  App/src/app/components/shared/aside/aside.component.html
  App/src/app/components/shared/aside/aside.component.ts
  App/src/app/components/success/success.component.css
  App/src/app/components/success/success.component.html
  App/src/app/components/success/success.component.ts
  App/src/app/components/transaction-list/transaction-list.component.ts
  App/src/app/models/create-payment-dto.ts
  App/src/app/services/account.service.ts
  App/src/app/services/payee.service.ts
  App/src/app/services/payment.service.ts
Labels: approved, lgtm, size/XXL

#86 Fix client features
  App/src/app/app-routing.module.ts
  App/src/app/components/account-creation/account-creation.component.ts
  App/src/app/components/account-management/account-management.component.ts
  App/src/app/components/cards/cards.component.html
  App/src/app/components/cards/cards.component.ts
  App/src/app/components/client-portal/client-portal.component.ts
  App/src/app/components/create-card/create-card.component.ts
  App/src/app/components/create-foreign-currency-account/create-foreign-currency-account.component.css
  App/src/app/components/create-foreign-currency-account/create-foreign-currency-account.component.ts
  App/src/app/components/edit-employee/edit-employee.component.html
  App/src/app/components/edit-user/edit-user.component.ts
  App/src/app/components/loan-request/loan-request.component.html
  App/src/app/components/loan-request/loan-request.component.ts
  App/src/app/components/loans/loans.component.html
  App/src/app/components/loans/loans.component.ts
  App/src/app/components/new-payment/new-payment.component.html
  App/src/app/components/register-user/register-user.component.ts
  App/src/app/components/shared/aside/aside.component.html
  App/src/app/components/shared/aside/aside.component.ts
  App/src/app/components/transfer/transfer.component.ts
  App/src/app/components/user-detail/user-detail.component.html
  App/src/app/components/user-detail/user-detail.component.ts
  App/src/app/components/users/users.component.css
  App/src/app/components/users/users.component.html
  App/src/app/components/users/users.component.ts
  App/src/app/models/loan-request.model.ts
  App/src/app/services/account.service.spec.ts
  App/src/app/services/account.service.ts
  App/src/app/services/auth.service.spec.ts
  App/src/app/services/card.service.ts
  App/src/app/services/client.service.ts
  App/src/app/services/employee.service.ts
  App/src/app/services/exchange.service.spec.ts
  App/src/app/services/loan-request.service.ts
  App/src/app/services/loan.service.spec.ts
  App/src/app/services/payee.service.spec.ts
  App/src/app/services/payment.service.ts
  package-lock.json
  package.json
Labels: size/XL, approved, lgtm

#88 New user fix
  App/src/app/app-routing.module.ts
  App/src/app/components/loan-details/loan-details.component.css
  App/src/app/components/loan-details/loan-details.component.html
  App/src/app/components/loan-details/loan-details.component.spec.ts
  App/src/app/components/loan-details/loan-details.component.ts
  App/src/app/components/loans/loans.component.html
  App/src/app/components/loans/loans.component.ts
  App/src/app/models/installment-model.ts
  App/src/app/services/card.service.ts
  App/src/app/services/loan-request.service.ts
  App/src/app/services/loan.service.ts
Labels: size/L, approved, lgtm

#87 F 75 moj portfolio
  App/src/app/app-routing.module.ts
  App/src/app/components/my-portfolio/my-portfolio.component.css
  App/src/app/components/my-portfolio/my-portfolio.component.html
  App/src/app/components/my-portfolio/my-portfolio.component.spec.ts
  App/src/app/components/my-portfolio/my-portfolio.component.ts
  App/src/app/models/securities.ts
  App/src/app/services/portfolio.service.spec.ts
  App/src/app/services/portfolio.service.ts
Labels: size/L, approved, lgtm

#90 New user fix
  App/src/app/components/account-management/account-management.component.html
  App/src/app/components/account-management/account-management.component.ts
  App/src/app/components/loan-details/loan-details.component.html
  App/src/app/components/loans/loans.component.ts
  App/src/app/components/new-payment/new-payment.component.html
  App/src/app/components/shared/aside/aside.component.html
  App/src/app/components/shared/aside/aside.component.ts
  App/src/app/components/transfer/transfer.component.ts
  App/src/app/models/account-response.model.ts
  App/src/app/services/account.service.ts
  App/src/app/services/card.service.ts
Labels: size/L, approved, lgtm

#89 F 78 Testiranje
  App/cypress.config.ts
  App/cypress/fixtures/example.json
  App/cypress/support/commands.ts
  App/cypress/support/component-index.html
  App/cypress/support/component.ts
  App/cypress/support/mock.ts
  App/cypress/tests/component/account-creation/account-creation.cy.ts
  App/cypress/tests/component/aside/aside.cy.ts
  App/cypress/tests/component/client-portal/client-portal.cy.ts
  App/cypress/tests/component/create-foreign-currency-account/foreign-account.cy.ts
  App/cypress/tests/component/edit-employee/edit-employee.cy.ts
  App/cypress/tests/component/edit-user/edit-user.cy.ts
  App/cypress/tests/component/register-employee/register-employee.cy.ts
  App/cypress/tests/component/register-user/register-user.cy.ts
  App/cypress/tests/e2e/client/login.spec.ts
  App/cypress/tests/e2e/employee/account.spec.ts
  App/cypress/tests/e2e/employee/login.spec.ts
  App/cypress/tests/e2e/employee/register.spec.ts
  App/cypress/tests/e2e/first.spec.ts
  App/package-lock.json
  App/package.json
Labels: approved, lgtm, size/XXL

#92 F x error fixing v4
  App/src/app/components/cards/cards.component.ts
  App/src/app/components/create-card/create-card.component.ts
  App/src/app/components/create-foreign-currency-account/create-foreign-currency-account.component.ts
  App/src/app/components/loan-request/loan-request.component.html
  App/src/app/components/loan-request/loan-request.component.ts
  App/src/app/components/register-user/register-user.component.html
  App/src/app/components/transfer/transfer.component.ts
  App/src/app/login/login.component.ts
  App/src/app/models/currency-dto.model.ts
  App/src/app/services/card.service.ts
  App/src/app/services/currency.service.ts
  App/src/app/services/loan-request.service.ts
Labels: size/L, approved, lgtm

#83 Implement securities portal with filtering, sorting, refresh
  App/src/app/app-routing.module.ts
  App/src/app/components/securities/securities.component.css
  App/src/app/components/securities/securities.component.html
  App/src/app/components/securities/securities.component.ts
  App/src/app/guards/securities.guard.ts
  App/src/app/models/security.model.ts
  App/src/app/services/auth.service.ts
  App/src/app/services/security.service.ts
Labels: size/L, approved, lgtm

#85 F 73 options detail
  App/src/app/app-routing.module.ts
  App/src/app/components/option/option.component.css
  App/src/app/components/option/option.component.html
  App/src/app/components/option/option.component.spec.ts
  App/src/app/components/option/option.component.ts
  App/src/app/models/option.model.ts
  App/src/app/services/option.service.ts
Labels: size/XL, approved, lgtm

#94 Napravljen prozor za order-e
  App/src/app/app-routing.module.ts
  App/src/app/components/order-overview/order-overview.component.css
  App/src/app/components/order-overview/order-overview.component.html
  App/src/app/components/order-overview/order-overview.component.ts
  App/src/app/models/order.model.ts
  App/src/app/services/order.service.ts
  package-lock.json
  package.json
Labels: size/L, approved, lgtm

#95 Modify authorized personnel handling for new account creation.
  App/src/app/components/account-creation/account-creation.component.html
  App/src/app/components/account-creation/account-creation.component.ts
  App/src/app/components/create-foreign-currency-account/create-foreign-currency-account.component.html
  App/src/app/components/create-foreign-currency-account/create-foreign-currency-account.component.ts
  App/src/app/models/new-bank-account.model.ts
Labels: approved, lgtm

#96 Admin error fix
  App/src/app/app-routing.module.ts
  App/src/app/components/account-management/account-management.component.html
  App/src/app/components/account-management/account-management.component.ts
  App/src/app/components/cards/cards.component.html
  App/src/app/components/cards/cards.component.ts
  App/src/app/components/client-portal/client-portal.component.html
  App/src/app/components/client-portal/client-portal.component.ts
  App/src/app/components/edit-employee/edit-employee.component.html
  App/src/app/components/edit-employee/edit-employee.component.ts
  App/src/app/components/employees/employees.component.css
  App/src/app/components/employees/employees.component.html
  App/src/app/components/employees/employees.component.ts
  App/src/app/components/exchage-rate-list/exchage-rate-list.component.ts
  App/src/app/components/loans/loans.component.ts
  App/src/app/components/new-loan-requests/new-loan-requests.component.css
  App/src/app/components/new-loan-requests/new-loan-requests.component.html
  App/src/app/components/new-loan-requests/new-loan-requests.component.spec.ts
  App/src/app/components/new-loan-requests/new-loan-requests.component.ts
  App/src/app/components/register-employee/register-employee.component.html
  App/src/app/components/register-employee/register-employee.component.ts
  App/src/app/components/shared/aside/aside.component.html
  App/src/app/components/shared/aside/aside.component.ts
  App/src/app/components/shared/navbar/navbar.component.ts
  App/src/app/components/transfer/transfer.component.ts
  App/src/app/models/account-details.ts
  App/src/app/models/account-dto.model.ts
  App/src/app/models/account-page-dto.model.ts
  App/src/app/models/card-dto.model.ts
  App/src/app/models/employee.model.ts
  App/src/app/models/loan-request.model.ts
  App/src/app/models/payment.model.ts
  App/src/app/models/transaction.model.ts
  App/src/app/models/transfer.model.ts
  App/src/app/services/card.service.ts
  App/src/app/services/employee.service.ts
  App/src/app/services/exchange.service.ts
  App/src/app/services/loan-request.service.ts
  App/src/app/services/loan.service.ts
  App/src/app/services/payment.service.ts
Labels: size/XL, approved, lgtm

#99 Fix cards
  App/src/app/components/cards/cards.component.css
  App/src/app/components/cards/cards.component.html
  App/src/app/components/cards/cards.component.ts
  App/src/app/components/create-card/create-card.component.html
  App/src/app/components/create-card/create-card.component.ts
  App/src/app/components/order-overview/order-overview.component.ts
  App/src/app/services/card.service.ts
Labels: size/L, approved, lgtm

#97 Small fix to make order component work.
  App/src/app/components/order-overview/order-overview.component.html
  App/src/app/components/order-overview/order-overview.component.ts
  App/src/app/models/order.model.ts
  App/src/app/services/order.service.ts
Labels: size/L, approved, lgtm

#100 Sync card logic with backend changes
  App/src/app/app-routing.module.ts
  App/src/app/components/account-creation/account-creation.component.html
  App/src/app/components/account-creation/account-creation.component.ts
  App/src/app/components/cards/cards.component.html
  App/src/app/components/cards/cards.component.ts
  App/src/app/components/create-foreign-currency-account/create-foreign-currency-account.component.ts
  App/src/app/components/loan-request/loan-request.component.ts
  App/src/app/components/new-loan-requests/new-loan-requests.component.html
  App/src/app/components/new-loan-requests/new-loan-requests.component.ts
  App/src/app/models/account.model.ts
  App/src/app/models/new-bank-account.model.ts
  App/src/app/services/account.service.ts
  App/src/app/services/loan-request.service.ts
Labels: size/L, approved, lgtm

#102 Fix
  App/src/app/components/account-management/account-management.component.html
  App/src/app/components/cards/cards.component.html
  App/src/app/components/cards/cards.component.ts
  App/src/app/components/loans/loans.component.html
  App/src/app/components/loans/loans.component.ts
Labels: approved, lgtm, size/M

#101 fix small bugs
  App/src/app/components/cards/cards.component.html
  App/src/app/components/cards/cards.component.ts
  App/src/app/components/employees/employees.component.html
  App/src/app/components/employees/employees.component.ts
  App/src/app/components/securities/securities.component.html
  App/src/app/components/securities/securities.component.ts
  App/src/app/components/shared/aside/aside.component.html
  App/src/app/services/payment.service.ts
Labels: size/L, approved, lgtm

#110 Add transaction overview and tax overview with filters part2
  App/src/app/app-routing.module.ts
  App/src/app/components/my-portfolio/my-portfolio.component.ts
  App/src/app/components/tax-calculation/tax-calculation.component.css
  App/src/app/components/tax-calculation/tax-calculation.component.html
  App/src/app/components/tax-calculation/tax-calculation.component.spec.ts
  App/src/app/components/tax-calculation/tax-calculation.component.ts
  App/src/app/models/securities-transaction.ts
  App/src/app/services/portfolio.service.ts
Labels: size/XL, approved, lgtm

#112 Fix securities & options components, fix route permissions
  App/src/app/app-routing.module.ts
  App/src/app/components/my-portfolio/my-portfolio.component.css
  App/src/app/components/my-portfolio/my-portfolio.component.html
  App/src/app/components/my-portfolio/my-portfolio.component.ts
  App/src/app/components/option/option.component.html
  App/src/app/components/order-overview/order-overview.component.html
  App/src/app/components/order-overview/order-overview.component.ts
  App/src/app/components/securities/securities.component.html
  App/src/app/components/securities/securities.component.ts
  App/src/app/guards/auth-guard.guard.ts
  App/src/app/guards/securities.guard.ts
  App/src/app/models/securities.ts
  App/src/app/services/auth.service.ts
  App/src/app/services/order.service.ts
  App/src/app/services/portfolio.service.ts
Labels: size/L, approved, lgtm

#113 Fix how the currencies are shown.
  App/src/app/components/cards/cards.component.html
  App/src/app/components/cards/cards.component.ts
  App/src/app/components/payment-details/payment-details.component.html
  App/src/app/components/payment-details/payment-details.component.ts
  App/src/app/components/transfer/transfer.component.html
  App/src/app/models/payment-overview-dto.ts
Labels: approved, lgtm, size/M

#115 Doradjen Actuary
  App/src/app/app-routing.module.ts
  App/src/app/components/actuary-management/actuary-management.component.css
  App/src/app/components/actuary-management/actuary-management.component.html
  App/src/app/components/actuary-management/actuary-management.component.ts
  App/src/app/services/actuary.service.ts
  package-lock.json
  package.json
Labels: size/L, approved, lgtm

#121 Implement order creation functionality
  App/src/app/components/my-portfolio/my-portfolio.component.html
  App/src/app/components/my-portfolio/my-portfolio.component.ts
  App/src/app/components/order-overview/order-overview.component.ts
  App/src/app/components/payment-details/payment-details.component.html
  App/src/app/components/securities/securities.component.html
  App/src/app/components/securities/securities.component.ts
  App/src/app/components/shared/order-creation-modal/order-creation-modal.component.css
  App/src/app/components/shared/order-creation-modal/order-creation-modal.component.html
  App/src/app/components/shared/order-creation-modal/order-creation-modal.component.spec.ts
  App/src/app/components/shared/order-creation-modal/order-creation-modal.component.ts
  App/src/app/components/shared/select/select.component.html
  App/src/app/components/transfer/transfer.component.ts
  App/src/app/models/create-order.dto.ts
  App/src/app/models/order.dto.ts
  App/src/app/models/order.model.ts
  App/src/app/models/securities.ts
  App/src/app/services/order.service.ts
  App/src/app/services/portfolio.service.ts
Labels: size/XL, approved, lgtm
