Repository RAF-SI-2024/Banka-3-Frontend, pull requests merged in 2025-04, with the labels that each got.

#132 Fix form field validation in new account forms
  App/src/app/components/account/account-creation/account-creation.component.html
  App/src/app/components/account/account-creation/account-creation.component.ts
  App/src/app/components/account/create-foreign-currency-account/create-foreign-currency-account.component.html
  App/src/app/components/account/create-foreign-currency-account/create-foreign-currency-account.component.ts
  App/src/app/components/shared/button/button.component.css
Labels: approved, lgtm, size/XXL

#135 Fix field validation and switch to reactive forms for a couple of components
  App/src/app/components/client/edit-user/edit-user.component.html
  App/src/app/components/client/edit-user/edit-user.component.ts
  App/src/app/components/payments/new-payment/new-payment.component.html
  App/src/app/components/payments/new-payment/new-payment.component.ts
  App/src/app/components/payments/recipients/recipients.component.html
  App/src/app/components/payments/recipients/recipients.component.ts
Labels: size/L, approved, lgtm

#140 F 131 Implement OTC offers page
  App/src/app/app-routing.module.ts
  App/src/app/components/shared/otc-offer-modal/otc-offer-modal.component.css
  App/src/app/components/shared/otc-offer-modal/otc-offer-modal.component.html
  App/src/app/components/shared/otc-offer-modal/otc-offer-modal.component.ts
  App/src/app/components/stocks/otc-offers-list/otc-offers-list.component.css
  App/src/app/components/stocks/otc-offers-list/otc-offers-list.component.html
  App/src/app/components/stocks/otc-offers-list/otc-offers-list.component.ts
  App/src/app/models/create-otc-offer.dto.ts
  App/src/app/models/otc-offer.dto.ts
  App/src/app/models/otc-offer.model.ts
  App/src/app/models/public-stock.dto.ts
  App/src/app/services/otc.service.ts
Labels: size/L, approved, lgtm

#143 uradjen profit banke i aktuari
  App/src/app/components/stocks/actuaries-agents/actuaries-agents.component.css
  App/src/app/components/stocks/actuaries-agents/actuaries-agents.component.html
  App/src/app/components/stocks/actuaries-agents/actuaries-agents.component.ts
  App/src/app/components/stocks/bank-profit/bank-profit.component.css
  App/src/app/components/stocks/bank-profit/bank-profit.component.html
  App/src/app/components/stocks/bank-profit/bank-profit.component.ts
  App/src/app/models/actuary-agent.dto.ts
  App/src/app/services/actuaries.service.ts
  package-lock.json
  package.json
Labels: size/L, approved, lgtm

#145 Fix
  App/src/app/app-routing.module.ts
  App/src/app/components/shared/order-creation-modal/order-creation-modal.component.html
  App/src/app/components/shared/order-creation-modal/order-creation-modal.component.ts
  App/src/app/components/stocks/my-portfolio/my-portfolio.component.html
  App/src/app/components/stocks/my-portfolio/my-portfolio.component.ts
  App/src/app/components/stocks/order-overview/order-overview.component.html
  App/src/app/components/stocks/order-overview/order-overview.component.ts
  App/src/app/components/stocks/securities/securities.component.ts
  App/src/app/models/order.dto.ts
  App/src/app/models/order.model.ts
  App/src/app/services/order.service.ts
  App/src/app/services/portfolio.service.ts
Labels: size/L, approved, lgtm

#152 Fix: tax flow
  App/src/app/components/tax-calculation/tax-calculation.component.css
  App/src/app/components/tax-calculation/tax-calculation.component.html
  App/src/app/components/tax-calculation/tax-calculation.component.ts
  App/src/app/services/tax.service.ts
Labels: size/L, approved, lgtm

#154 Implement and fix securities details and options flow
  App/src/app/app-routing.module.ts
  App/src/app/components/stocks/option/option.component.html
  App/src/app/components/stocks/option/option.component.spec.ts
  App/src/app/components/stocks/option/option.component.ts
  App/src/app/components/stocks/securities/securities.component.html
  App/src/app/components/stocks/securities/securities.component.ts
  App/src/app/components/stocks/stock-date-details/stock-date-details.component.css
  App/src/app/components/stocks/stock-date-details/stock-date-details.component.html
  App/src/app/components/stocks/stock-date-details/stock-date-details.component.ts
  App/src/app/components/stocks/stock-details/stock-details.component.css
  App/src/app/components/stocks/stock-details/stock-details.component.html
  App/src/app/components/stocks/stock-details/stock-details.component.ts
  App/src/app/enums/listing-type.enum.ts
  App/src/app/guards/actuary-guard.guard.ts
  App/src/app/models/create-order.dto.ts
  App/src/app/models/listing-details.dto.ts
  App/src/app/models/price-history.dto.ts
  App/src/app/services/option.service.ts
  App/src/app/services/security.service.ts
Labels: approved, lgtm, size/XXL

#153 Remove random component
  App/src/app/components/stocks/actuaries-agents/actuaries-agents.component.css
  App/src/app/components/stocks/actuaries-agents/actuaries-agents.component.html
  App/src/app/components/stocks/actuaries-agents/actuaries-agents.component.ts
Labels: size/L, approved, lgtm

#125 F 117 cypress cicd
  .dockerignore
  .gitignore
  .prow/build.yaml
  .prow/test.yaml
  App/cypress.config.ts
  App/cypress/support/commands.ts
  App/cypress/tests/e2e/account.spec.ts
  App/cypress/tests/e2e/cards.spec.ts
  App/cypress/tests/e2e/checking_account.spec.ts
  App/cypress/tests/e2e/employee_and_user_manipulation.spec.ts
  App/cypress/tests/e2e/foreign_account.spec.ts
  App/cypress/tests/e2e/loan_request.spec.ts
  App/cypress/tests/e2e/login.spec.ts
  App/cypress/tests/e2e/stock-options.spec.ts
  App/cypress/tests/e2e/welcome.spec.ts
  App/package-lock.json
  App/package.json
  App/src/app/components/account/account-creation/account-creation.component.html
  App/src/app/components/account/account-management/account-management.component.html
  App/src/app/components/account/bank-accounts/bank-accounts.component.html
  App/src/app/components/account/cards/cards.component.html
  App/src/app/components/account/cards/cards.component.ts
  App/src/app/components/account/create-foreign-currency-account/create-foreign-currency-account.component.html
  App/src/app/components/payments/transfer/transfer.component.html
  App/src/app/components/shared/order-creation-modal/order-creation-modal.component.html
  App/src/app/components/tax-calculation/tax-calculation.component.html
  App/src/app/services/account.service.ts
  App/src/app/services/auth.service.ts
  App/target/site/jacoco/results.xml
  DockerFileTest
  Dockerfile
  docker-compose.prod.yml
  docker-compose.test.yml
  docker-compose.yml
  nginx-default.conf
Labels: approved, lgtm, size/XXL

#156 F env cicd
  .gitignore
  .prow/test.yaml
  App/.env.example
  App/angular.json
  App/cypress/tests/e2e/stock-options.spec.ts
  App/package-lock.json
  App/package.json
  App/src/app/environments/environment.development.ts
  App/src/app/environments/environment.ts
  App/src/app/services/account.service.ts
  App/src/app/services/actuaries.service.ts
  App/src/app/services/actuary.service.ts
  App/src/app/services/auth.service.ts
  App/src/app/services/authorized-personnel.service.spec.ts
  App/src/app/services/authorized-personnel.service.ts
  App/src/app/services/card.service.ts
  App/src/app/services/client.service.ts
  App/src/app/services/company.service.spec.ts
  App/src/app/services/company.service.ts
  App/src/app/services/contracts.service.ts
  App/src/app/services/employee.service.ts
  App/src/app/services/exchange.service.ts
  App/src/app/services/loan-request.service.ts
  App/src/app/services/loan.service.ts
  App/src/app/services/option.service.ts
  App/src/app/services/order.service.ts
  App/src/app/services/otc.service.ts
  App/src/app/services/payee.service.ts
  App/src/app/services/payment.service.ts
  App/src/app/services/portfolio.service.spec.ts
  App/src/app/services/portfolio.service.ts
  App/src/app/services/security.service.ts
  App/src/app/services/tax.service.ts
  App/src/scripts/generate-env-local.ts
  App/src/scripts/generate-env.ts
  App/target/site/jacoco/results.xml
  docker-compose.test.yml
  docker-compose.yml
Labels: size/XL, approved, lgtm

#155 Bank profile Reimplementacija
  App/src/app/components/stocks/bank-profit/bank-profit.component.html
  App/src/app/components/stocks/bank-profit/bank-profit.component.ts
  App/src/app/components/stocks/order-overview/order-overview.component.html
  App/src/app/components/stocks/order-overview/order-overview.component.ts
  App/src/app/models/order.dto.ts
  App/src/app/models/order.model.ts
  App/src/app/services/actuaries.service.ts
Labels: size/L, approved, lgtm

#157 test
  App/.env.example
  App/angular.json
  App/package.json
  App/src/app/environments/environment.development.ts
  DockerFileTest
  Dockerfile
  docker-compose.prod.yml
  docker-compose.yml
Labels: approved, lgtm, size/M

#158 fix
  App/cypress/tests/e2e/cards.spec.ts
  App/cypress/tests/e2e/checking_account.spec.ts
  App/cypress/tests/e2e/employee_and_user_manipulation.spec.ts
  App/cypress/tests/e2e/foreign_account.spec.ts
  App/cypress/tests/e2e/loan_request.spec.ts
  App/cypress/tests/e2e/login.spec.ts
  App/cypress/tests/e2e/welcome.spec.ts
  App/package-lock.json
  App/package.json
  App/src/app/environments/environment.ts
  App/src/scripts/generate-env.ts
  App/target/site/jacoco/results.xml
Labels: size/L, approved, lgtm

#161 Big fix
  App/cypress/tests/e2e/cards.spec.ts
  App/src/app/app-routing.module.ts
  App/src/app/components/account/account-creation/account-creation.component.html
  App/src/app/components/account/account-creation/account-creation.component.ts
  App/src/app/components/account/account-management/account-management.component.html
  App/src/app/components/account/cards/cards.component.html
  App/src/app/components/account/create-foreign-currency-account/create-foreign-currency-account.component.html
  App/src/app/components/account/create-foreign-currency-account/create-foreign-currency-account.component.ts
  App/src/app/components/employee/employees/employees.component.html
  App/src/app/components/employee/employees/employees.component.ts
  App/src/app/components/shared/navbar/navbar.component.html
  App/src/app/components/shared/otc-offer-modal/otc-offer-modal.component.html
  App/src/app/components/shared/otc-offer-modal/otc-offer-modal.component.ts
  App/src/app/components/stocks/actuary-management/actuary-management.component.html
  App/src/app/components/stocks/bank-profit/bank-profit.component.ts
  App/src/app/components/stocks/order-overview/order-overview.component.html
  App/src/app/components/stocks/order-overview/order-overview.component.ts
  App/src/app/components/stocks/securities/securities.component.html
  App/src/app/components/stocks/settled-contracts/settled-contracts.component.html
  App/src/app/components/stocks/settled-contracts/settled-contracts.component.ts
  App/src/app/components/stocks/stock-details/stock-details.component.html
  App/src/app/components/tax-calculation/tax-calculation.component.html
  App/src/app/components/tax-calculation/tax-calculation.component.ts
  App/src/app/models/order.dto.ts
  App/src/app/models/order.model.ts
  App/src/app/models/settled-contract-dto.ts
  App/src/app/services/account.service.ts
  App/src/app/services/actuaries.service.ts
  App/src/app/services/actuary.service.ts
  App/src/app/services/portfolio.service.ts
Labels: size/L, approved, lgtm

#162 Add Use Option in Portfolio
  App/src/app/components/shared/order-creation-modal/order-creation-modal.component.ts
  App/src/app/components/stocks/my-portfolio/my-portfolio.component.html
  App/src/app/components/stocks/my-portfolio/my-portfolio.component.ts
  App/src/app/components/stocks/settled-contracts/settled-contracts.component.ts
  App/src/app/enums/listing-type.enum.ts
  App/src/app/models/my-portfolio.ts
  App/src/app/services/portfolio.service.ts
Labels: approved, lgtm, size/M

#167 Fix
  App/src/app/components/stocks/bank-profit/bank-profit.component.html
  App/src/app/components/stocks/bank-profit/bank-profit.component.ts
  App/src/app/components/tax-calculation/tax-calculation.component.html
  App/src/app/components/tax-calculation/tax-calculation.component.ts
  App/src/app/services/actuaries.service.ts
Labels: size/L, approved, lgtm

#165 F x fixeS v1
  App/cypress/tests/e2e/checking_account.spec.ts
  App/cypress/tests/e2e/foreign_account.spec.ts
  App/src/app/components/account/account-creation/account-creation.component.html
  App/src/app/components/account/account-creation/account-creation.component.ts
  App/src/app/components/account/cards/cards.component.html
  App/src/app/components/account/cards/cards.component.ts
  App/src/app/components/account/create-card/create-card.component.css
  App/src/app/components/account/create-card/create-card.component.html
  App/src/app/components/account/create-card/create-card.component.ts
  App/src/app/components/account/create-foreign-currency-account/create-foreign-currency-account.component.html
  App/src/app/components/account/create-foreign-currency-account/create-foreign-currency-account.component.ts
  App/src/app/components/shared/autocomplete-text/autocomplete-text.component.css
  App/src/app/components/shared/autocomplete-text/autocomplete-text.component.html
  App/src/app/components/shared/autocomplete-text/autocomplete-text.component.spec.ts
  App/src/app/components/shared/autocomplete-text/autocomplete-text.component.ts
  App/src/app/services/card.service.ts
Labels: size/XL, approved, lgtm

#172 F cypress
  .prow/test.yaml
  App/cypress/tests/e2e/cards.spec.ts
  App/cypress/tests/e2e/checking_account.spec.ts
  App/cypress/tests/e2e/foreign_account.spec.ts
  App/src/app/components/account/bank-accounts/bank-accounts.component.css
  package-lock.json
  package.json
Labels: size/L, approved, lgtm

#173 F x fixe s v2
  App/src/app/components/stocks/stock-date-details/stock-date-details.component.css
  App/src/app/components/stocks/stock-date-details/stock-date-details.component.html
  App/src/app/components/stocks/stock-date-details/stock-date-details.component.ts
  App/src/app/services/contracts.service.ts
Labels: size/L, approved, lgtm

#171 Implement new screen for my orders, simple testing is done, made new OrderRealDto to match the one from the backend, final testig still left to do..
  App/src/app/app-routing.module.ts
  App/src/app/components/stocks/my-orders/my-orders.component.css
  App/src/app/components/stocks/my-orders/my-orders.component.html
  App/src/app/components/stocks/my-orders/my-orders.component.spec.ts
  App/src/app/components/stocks/my-orders/my-orders.component.ts
  App/src/app/components/stocks/my-portfolio/my-portfolio.component.ts
  App/src/app/models/order-real-dto.ts
  App/src/app/models/order.dto.ts
  App/src/app/services/order.service.ts
Labels: size/L, approved, lgtm

#174 FixeS_V3
  App/package-lock.json
  App/package.json
  App/src/app/components/stocks/active-offers/active-offers.component.html
  App/src/app/components/stocks/active-offers/active-offers.component.ts
  App/src/app/components/stocks/bank-profit/bank-profit.component.html
  App/src/app/components/stocks/bank-profit/bank-profit.component.ts
  App/src/app/components/stocks/my-portfolio/my-portfolio.component.html
  App/src/app/components/stocks/stock-date-details/stock-date-details.component.html
  App/src/app/components/stocks/stock-date-details/stock-date-details.component.ts
  App/src/app/models/active-offer.dto.ts
  App/src/app/models/my-portfolio.ts
  App/src/app/models/option.model.ts
  App/src/app/services/active-offers.service.ts
  App/src/app/services/portfolio.service.ts
  App/src/app/services/tax.service.ts
Labels: size/L, approved, lgtm

#175 Fix All
  App/package-lock.json
  App/package.json
  App/src/app/app-routing.module.ts
  App/src/app/components/shared/aside/aside.component.html
  App/src/app/components/shared/aside/aside.component.ts
  App/src/app/components/stocks/actuary-management/actuary-management.component.ts
  App/src/app/components/stocks/my-orders/my-orders.component.html
  App/src/app/components/stocks/securities/securities.component.html
  App/src/app/components/stocks/stock-details/stock-details.component.html
  App/src/app/components/stocks/stock-details/stock-details.component.ts
  App/src/app/models/time-series.model.ts
  App/src/app/services/security.service.ts
  App/tsconfig.app.json
Labels: size/L, approved, lgtm

#176 Add deploy job
  .prow/deploy.yaml
Labels: approved, size/M

#177 Fix deploy job
  .prow/deploy.yaml
Labels: size/XS, approved

#178 Fix All
  App/cypress/tests/component/account-creation/account-creation.cy.ts
  App/cypress/tests/component/create-foreign-currency-account/foreign-account.cy.ts
  App/cypress/tests/e2e/checking_account.spec.ts
  App/cypress/tests/e2e/employee_and_user_manipulation.spec.ts
  App/cypress/tests/e2e/foreign_account.spec.ts
  App/cypress/tests/e2e/loan_request.spec.ts
  App/src/app/app-routing.module.ts
  App/src/app/components/account/account-creation/account-creation.component.html
  App/src/app/components/account/account-creation/account-creation.component.ts
  App/src/app/components/account/account-management/account-management.component.html
  App/src/app/components/account/account-management/account-management.component.ts
  App/src/app/components/account/cards/cards.component.html
  App/src/app/components/account/cards/cards.component.ts
  App/src/app/components/account/create-foreign-currency-account/create-foreign-currency-account.component.html
  App/src/app/components/account/create-foreign-currency-account/create-foreign-currency-account.component.ts
  App/src/app/components/client/register-user/register-user.component.html
  App/src/app/components/client/register-user/register-user.component.ts
  App/src/app/components/loan/loan-request/loan-request.component.ts
  App/src/app/components/shared/aside/aside.component.html
  App/src/app/components/shared/aside/aside.component.ts
  App/src/app/components/stocks/my-portfolio/my-portfolio.component.html
  App/src/app/components/stocks/my-portfolio/my-portfolio.component.ts
  App/src/app/components/stocks/securities/securities.component.html
  App/src/app/components/stocks/securities/securities.component.ts
  App/src/app/components/stocks/stock-date-details/stock-date-details.component.css
  App/src/app/components/stocks/stock-date-details/stock-date-details.component.html
  App/src/app/components/stocks/stock-date-details/stock-date-details.component.ts
  App/src/app/components/stocks/stock-details/stock-details.component.html
  App/src/app/components/stocks/stock-details/stock-details.component.ts
  App/src/app/models/account-response.model.ts
  App/src/app/models/account-transfer.ts
  App/src/app/models/loan-dto.model.ts
  App/src/app/models/loan-request.model.ts
  App/src/app/models/new-bank-account.model.ts
  App/src/app/services/account.service.ts
  App/src/app/services/security.service.ts
Labels: size/XL, approved, lgtm

#180 cleanup sidebar
  App/cypress/tests/e2e/employee_and_user_manipulation.spec.ts
  App/src/app/app.component.css
  App/src/app/app.component.html
  App/src/app/components/shared/aside/aside.component.css
  App/src/app/components/shared/aside/aside.component.html
  App/src/app/components/shared/aside/aside.component.ts
Labels: size/XL, approved, lgtm

#181 chart js impl
  App/package-lock.json
  App/package.json
  App/src/app/app.config.ts
  App/src/app/components/stocks/stock-details/stock-details.component.html
  App/src/app/components/stocks/stock-details/stock-details.component.ts
  App/src/app/models/price-history.dto.ts
Labels: size/XL, approved, lgtm

#182 F dizajn
  App/src/app/components/shared/alert/alert.component.css
  App/src/app/components/shared/button/button.component.css
  App/src/app/components/shared/button/button.component.html
  App/src/app/components/shared/button/button.component.ts
  App/src/app/components/stocks/active-offers/active-offers.component.html
  App/src/app/components/stocks/actuary-management/actuary-management.component.css
  App/src/app/components/stocks/actuary-management/actuary-management.component.html
  App/src/app/components/stocks/actuary-management/actuary-management.component.ts
  App/src/app/components/stocks/bank-profit/bank-profit.component.css
  App/src/app/components/stocks/bank-profit/bank-profit.component.html
  App/src/app/components/stocks/my-portfolio/my-portfolio.component.css
  App/src/app/components/stocks/my-portfolio/my-portfolio.component.html
  App/src/app/components/stocks/otc-offers-list/otc-offers-list.component.css
  App/src/app/components/stocks/otc-offers-list/otc-offers-list.component.html
  App/src/app/components/stocks/securities/securities.component.html
  App/src/app/components/stocks/securities/securities.component.ts
  App/src/app/login/login.component.css
  App/src/app/login/login.component.html
  App/src/app/login/login.component.ts
  App/src/assets/css/tag.css
  App/src/styles.css
Labels: approved, lgtm, size/XXL

#186 loan button
  App/src/app/components/client/client-portal/client-portal.component.html
  App/src/app/components/shared/aside/aside.component.html
Labels: size/XS, approved, lgtm

#187 Fix orders sidebar button
  App/src/app/components/shared/aside/aside.component.html
  App/src/app/components/shared/aside/aside.component.ts
Labels: size/XS, approved, lgtm
